export const GITHUB_EMOJI_MAP: Record<string, string> = {
	bowtie: "🎩",
	smile: "😄",
	laughing: "😆",
	blush: "😊",
	smiley: "😃",
	relaxed: "☺️",
	smirk: "😏",
	heart_eyes: "😍",
	kissing_heart: "😘",
	kissing_closed_eyes: "😚",
	flushed: "😳",
	relieved: "😌",
	satisfied: "😆",
	grin: "😁",
	wink: "😉",
	stuck_out_tongue_winking_eye: "😜",
	stuck_out_tongue_closed_eyes: "😝",
	grinning: "😀",
	kissing: "😗",
	kissing_smiling_eyes: "😙",
	stuck_out_tongue: "😛",
	sleeping: "😴",
	worried: "😟",
	frowning: "😦",
	anguished: "😧",
	open_mouth: "😮",
	grimacing: "😬",
	confused: "😕",
	hushed: "😯",
	expressionless: "😑",
	unamused: "😒",
	sweat_smile: "😅",
	sweat: "😓",
	disappointed_relieved: "😥",
	weary: "😩",
	pensive: "😔",
	disappointed: "😞",
	confounded: "😖",
	fearful: "😨",
	cold_sweat: "😰",
	persevere: "😣",
	cry: "😢",
	sob: "😭",
	joy: "😂",
	astonished: "😲",
	scream: "😱",
	tired_face: "😫",
	angry: "😠",
	rage: "😡",
	triumph: "😤",
	sleepy: "😪",
	yum: "😋",
	mask: "😷",
	sunglasses: "😎",
	dizzy_face: "😵",
	imp: "👿",
	smiling_imp: "😈",
	neutral_face: "😐",
	no_mouth: "😶",
	innocent: "😇",
	alien: "👽",
	yellow_heart: "💛",
	blue_heart: "💙",
	purple_heart: "💜",
	heart: "❤️",
	green_heart: "💚",
	broken_heart: "💔",
	heartbeat: "💓",
	heartpulse: "💗",
	two_hearts: "💕",
	revolving_hearts: "💞",
	cupid: "💘",
	sparkling_heart: "💖",
	sparkles: "✨",
	star: "⭐",
	star2: "🌟",
	dizzy: "💫",
	boom: "💥",
	collision: "💥",
	anger: "💢",
	exclamation: "❗",
	question: "❓",
	grey_exclamation: "❕",
	grey_question: "❔",
	zzz: "💤",
	dash: "💨",
	sweat_drops: "💦",
	notes: "🎶",
	musical_note: "🎵",
	fire: "🔥",
	poop: "💩",
	thumbsup: "👍",
	"+1": "👍",
	thumbsdown: "👎",
	"-1": "👎",
	ok_hand: "👌",
	punch: "👊",
	fist: "✊",
	v: "✌️",
	wave: "👋",
	hand: "✋",
	raised_hand: "✋",
	open_hands: "👐",
	point_up: "☝️",
	point_down: "👇",
	point_left: "👈",
	point_right: "👉",
	raised_hands: "🙌",
	pray: "🙏",
	point_up_2: "👆",
	clap: "👏",
	muscle: "💪",
	metal: "🤘",
	walking: "🚶",
	runner: "🏃",
	running: "🏃",
	dancer: "💃",
	boy: "👦",
	girl: "👧",
	woman: "👩",
	man: "👨",
	baby: "👶",
	angel: "👼",
	skull: "💀",
	lips: "👄",
	kiss: "💋",
	eyes: "👀",
	tongue: "👅",
	love_letter: "💌",
	speech_balloon: "💬",
	thought_balloon: "💭",
	sunny: "☀️",
	umbrella: "☔",
	cloud: "☁️",
	snowflake: "❄️",
	snowman: "⛄",
	zap: "⚡",
	cyclone: "🌀",
	ocean: "🌊",
	cat: "🐱",
	dog: "🐶",
	mouse: "🐭",
	hamster: "🐹",
	rabbit: "🐰",
	wolf: "🐺",
	frog: "🐸",
	tiger: "🐯",
	koala: "🐨",
	bear: "🐻",
	pig: "🐷",
	monkey_face: "🐵",
	monkey: "🐒",
	horse: "🐴",
	snake: "🐍",
	bird: "🐦",
	penguin: "🐧",
	turtle: "🐢",
	bug: "🐛",
	octopus: "🐙",
	fish: "🐟",
	whale: "🐳",
	dolphin: "🐬",
	dragon: "🐉",
	bouquet: "💐",
	cherry_blossom: "🌸",
	tulip: "🌷",
	four_leaf_clover: "🍀",
	rose: "🌹",
	sunflower: "🌻",
	maple_leaf: "🍁",
	fallen_leaf: "🍂",
	herb: "🌿",
	mushroom: "🍄",
	cactus: "🌵",
	palm_tree: "🌴",
	seedling: "🌱",
	sun_with_face: "🌞",
	full_moon_with_face: "🌝",
	crescent_moon: "🌙",
	earth_americas: "🌎",
	volcano: "🌋",
	milky_way: "🌌",
	tomato: "🍅",
	watermelon: "🍉",
	banana: "🍌",
	apple: "🍎",
	green_apple: "🍏",
	peach: "🍑",
	cherries: "🍒",
	strawberry: "🍓",
	hamburger: "🍔",
	pizza: "🍕",
	rice: "🍚",
	ramen: "🍜",
	spaghetti: "🍝",
	bread: "🍞",
	fries: "🍟",
	sushi: "🍣",
	icecream: "🍦",
	doughnut: "🍩",
	cookie: "🍪",
	chocolate_bar: "🍫",
	candy: "🍬",
	cake: "🍰",
	coffee: "☕",
	tea: "🍵",
	beer: "🍺",
	wine_glass: "🍷",
	cocktail: "🍸",
	tropical_drink: "🍹",
	ribbon: "🎀",
	gift: "🎁",
	birthday: "🎂",
	jack_o_lantern: "🎃",
	christmas_tree: "🎄",
	santa: "🎅",
	fireworks: "🎆",
	balloon: "🎈",
	tada: "🎉",
	confetti_ball: "🎊",
	trophy: "🏆",
	soccer: "⚽",
	basketball: "🏀",
	football: "🏈",
	tennis: "🎾",
	dart: "🎯",
	golf: "⛳",
	video_game: "🎮",
	art: "🎨",
	microphone: "🎤",
	headphones: "🎧",
	guitar: "🎸",
	clapper: "🎬",
	checkered_flag: "🏁",
	warning: "⚠️",
	x: "❌",
	o: "⭕",
	no_entry: "⛔",
	heavy_check_mark: "✔️",
	white_check_mark: "✅",
	recycle: "♻️",
	rocket: "🚀",
	airplane: "✈️",
	car: "🚗",
	bus: "🚌",
	train: "🚂",
	ship: "🚢",
	anchor: "⚓",
	construction: "🚧",
	house: "🏠",
	hospital: "🏥",
	watch: "⌚",
	hourglass: "⌛",
	alarm_clock: "⏰",
	lock: "🔒",
	unlock: "🔓",
	key: "🔑",
	bulb: "💡",
	wrench: "🔧",
	hammer: "🔨",
	bomb: "💣",
	pill: "💊",
	moneybag: "💰",
	dollar: "💵",
	gem: "💎",
	ring: "💍",
	crown: "👑",
	eyeglasses: "👓",
	computer: "💻",
	iphone: "📱",
	camera: "📷",
	tv: "📺",
	mag: "🔍",
	bell: "🔔",
	bookmark: "🔖",
	link: "🔗",
	books: "📚",
	book: "📖",
	memo: "📝",
	pencil: "📝",
	clipboard: "📋",
	calendar: "📆",
	pushpin: "📌",
	envelope: "✉️",
	package: "📦",
	label: "🏷️",
	scissors: "✂️",
	100: "💯",
	heavy_plus_sign: "➕",
	heavy_minus_sign: "➖",
	arrow_up: "⬆️",
	arrow_down: "⬇️",
	arrow_left: "⬅️",
	arrow_right: "➡️",
	red_circle: "🔴",
	large_blue_circle: "🔵",
	white_circle: "⚪",
	black_circle: "⚫",
	see_no_evil: "🙈",
	hear_no_evil: "🙉",
	speak_no_evil: "🙊",
}

export const EMOJI_CATEGORIES: Record<string, string[]> = {
	Smileys: [
		"smile",
		"laughing",
		"blush",
		"smiley",
		"grinning",
		"wink",
		"heart_eyes",
		"kissing_heart",
		"sunglasses",
		"smirk",
		"joy",
		"sweat_smile",
		"innocent",
		"cry",
		"sob",
		"angry",
		"rage",
		"scream",
		"sleeping",
		"mask",
		"imp",
		"neutral_face",
		"confused",
		"worried",
		"pensive",
		"yum",
		"stuck_out_tongue",
	],
	Gestures: [
		"thumbsup",
		"thumbsdown",
		"ok_hand",
		"punch",
		"fist",
		"v",
		"wave",
		"raised_hands",
		"pray",
		"clap",
		"muscle",
		"point_up",
		"point_down",
		"point_left",
		"point_right",
		"metal",
	],
	"Hearts & Symbols": [
		"heart",
		"yellow_heart",
		"blue_heart",
		"purple_heart",
		"green_heart",
		"broken_heart",
		"sparkling_heart",
		"two_hearts",
		"sparkles",
		"star",
		"fire",
		"boom",
		"zap",
		"100",
		"heavy_check_mark",
		"white_check_mark",
		"x",
		"warning",
		"exclamation",
		"question",
	],
	Animals: [
		"cat",
		"dog",
		"mouse",
		"hamster",
		"rabbit",
		"wolf",
		"frog",
		"tiger",
		"koala",
		"bear",
		"pig",
		"monkey_face",
		"horse",
		"snake",
		"bird",
		"penguin",
		"turtle",
		"bug",
		"octopus",
		"fish",
		"whale",
		"dolphin",
		"dragon",
	],
	Nature: [
		"sunny",
		"cloud",
		"umbrella",
		"snowflake",
		"zap",
		"ocean",
		"cyclone",
		"cherry_blossom",
		"rose",
		"sunflower",
		"tulip",
		"four_leaf_clover",
		"maple_leaf",
		"fallen_leaf",
		"herb",
		"mushroom",
		"cactus",
		"palm_tree",
		"seedling",
		"crescent_moon",
		"earth_americas",
		"volcano",
	],
	"Food & Drink": [
		"apple",
		"banana",
		"watermelon",
		"strawberry",
		"cherries",
		"peach",
		"pizza",
		"hamburger",
		"fries",
		"sushi",
		"ramen",
		"spaghetti",
		"cake",
		"icecream",
		"doughnut",
		"cookie",
		"chocolate_bar",
		"candy",
		"coffee",
		"tea",
		"beer",
		"wine_glass",
		"cocktail",
		"tropical_drink",
	],
	Objects: [
		"rocket",
		"computer",
		"iphone",
		"camera",
		"bulb",
		"wrench",
		"hammer",
		"key",
		"lock",
		"gem",
		"crown",
		"book",
		"books",
		"memo",
		"clipboard",
		"calendar",
		"pushpin",
		"envelope",
		"package",
		"bell",
		"bookmark",
		"link",
		"scissors",
		"mag",
		"eyeglasses",
		"moneybag",
	],
	Celebrations: [
		"tada",
		"confetti_ball",
		"balloon",
		"gift",
		"birthday",
		"fireworks",
		"christmas_tree",
		"santa",
		"trophy",
		"ribbon",
		"dart",
		"clapper",
		"art",
		"microphone",
		"guitar",
		"video_game",
	],
}
